import { Product } from '../entities/Product';
import catImage from '../features/ProductCard/assets/Cat.svg';

export const mockProducts: Product[] = [
  {
    id: 1,
    subtitle: 'Сказочное заморское яство',
    title: 'Нямушка',
    flavor: 'с фуа-гра',
    special: ['10 порций', 'мышь в подарок'],
    weight: '0,5',
    weightUnit: 'кг',
    text: 'Чего сидишь? Порадуй котэ, ',
    link: 'купи.',
    image: catImage,
    selected: false,
    discription: 'Печень утки разварная с артишоками.',
    isOutOffStock: false,
    outOffStockLabel: 'Печалька, с фуа-гра закончился.',
  },
  {
    id: 2,
    subtitle: 'Сказочное заморское яство',
    title: 'Нямушка',
    flavor: 'с рыбой',
    special: ['40 порций', '2 мыши в подарок'],
    weight: '2',
    weightUnit: 'кг',
    text: 'Чего сидишь? Порадуй котэ, ',
    link: 'купи.',
    image: catImage,
    selected: false,
    discription: 'Головы щучьи с чесноком да свежайшая сёмгушка.',
    isOutOffStock: false,
    outOffStockLabel: 'Печалька, с рыбой закончился.',
  },
  {
    id: 3,
    subtitle: 'Сказочное заморское яство',
    title: 'Нямушка',
    flavor: 'с курой',
    special: ['100 порций', '5 мышей в подарок', 'заказчик доволен'],
    weight: '5',
    weightUnit: 'кг',
    text: 'Чего сидишь? Порадуй котэ, ',
    link: 'купи.',
    image: catImage,
    selected: false,
    discription: 'Филе из цыплят с трюфелями в бульоне.',
    isOutOffStock: true,
    outOffStockLabel: 'Печалька, с курой закончился.',
  },
  // {
  //   id: 5,
  //   subtitle: 'Сказочное заморское яство',
  //   title: 'Нямушка',
  //   flavor: 'с курой',
  //   special: ['100 порций', '5 мышей в подарок', 'заказчик доволен'],
  //   weight: '5',
  //   weightUnit: 'кг',
  //   text: 'Чего сидишь? Порадуй котэ, ',
  //   link: 'купи.',
  //   image: catImage,
  //   selected: false,
  //   discription: 'Филе из цыплят с трюфелями в бульоне.',
  //   isOutOffStock: false,
  //   outOffStockLabel: 'Печалька, с курой закончился.',
  // },
];
